### ISSUE TITLE
With version 0.4.1 dist/main.js is not served the request fails with 404

### ISSUE THREAD

**Issue by sharpoverride** [zewa666/generator-aurelia#11]
The reason seems to be that config.js has a missing .js in paths: {'_' : "dist/_"}

it should be paths: {"_": "dist/_.js"}

**Comment by zewa666** [comment]
That's not related to the generator itself, it sounds like you maybe haven't updated JSPM to beta before running the generator. There was a recent release for Aurelia requiring JSPM@beta. In order to make that work try updating JSPM with this command `npm install -g jspm@beta` and then execute the generator again.
