### ISSUE TITLE
dist/aurelia.js not found when executes gulp watch.

### ISSUE THREAD

**Issue by emaung** [zewa666/generator-aurelia#22]
Hi,

I am having an error saying 404 not found for dist/aurelia.js when I run "gulp watch"

Currently, it works only if I add a "bundle" task to "build" one as dependency. Am I missing something or is it supposed to be like that?

Cheers,
Tin

**Comment by zewa666** [comment]
to be honest I haven't looked into the bundled scenario at all, since most of the times this is used only for production sites without the need for browsersync etc. I'm pretty sure the skeleton navs tasks have been updated to provide support for that, if you have time you could look it up and create a PR for the generator so we get the feature in here as well.

**Comment by eskalera** [comment]
Same issue here. @tinhtooaung, how did you add it as a dependency? I tried

gulp.task('build', ['bundle'], ....

but still getting an Error: ENOENT: no such file or directory.

**Comment by emaung** [comment]
HI @eskalera Here is what I got

gulp.task('build', function(callback) {
  return runSequence(
    'clean',
    ['build-system', 'build-html', 'build-css', 'bundle'],
    callback
  );
});

**Comment by eskalera** [comment]
Thanks @tinhtooaung. It works now.
